### ISSUE TITLE
Need more resources -- Tutorials

### ISSUE THREAD

**Issue by gnuself** [gnuself/linux-is-free#3]
Might be beneficial to link to helpful tutorials for Linux newbies.

**Comment by Danushka96** [comment]
I will work on this one.

**Comment by Danushka96** [comment]
Do you want to Write tutorials or add some tutorial links to the readme file?

**Comment by gnuself** [comment]
Hi, thanks for reaching out. I would prefer links to tutorials in an effort to keep the pages clean for now. And please add that these to resources.md, so that those browsing the site for more info would be able to find those tutorials there.

**Comment by gnuself** [comment]
Please break out links one per line with two trailing spaces after each item.

**Comment by Danushka96** [comment]
Sure.

**Comment by gnuself** [comment]
Appreciate the start of work on this one, but I am open to more contributions.
